language: node_js
node_js: node

sudo: required  # for docker
services:
  - docker

script:
  - docker build -f docker/Dockerfile -t lfweb .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == develop -a "$TRAVIS_PULL_REQUEST" == false ]; then
      docker tag lfweb epilanthanomai/lfweb:dev;
      docker push epilanthanomai/lfweb:dev;
    fi
  - if [ "$TRAVIS_BRANCH" == master ]; then
      docker tag lfweb epilanthanomai/lfweb;
      docker push epilanthanomai/lfweb;
    fi
  - if [ -n "$TRAVIS_TAG" ]; then
      docker tag lfweb epilanthanomai/lfweb:$TRAVIS_TAG;
      docker push epilanthanomai/lfweb:$TRAVIS_TAG;
    fi

notifications:
  email: false
