version: '2'
services:
  root:
    depends_on:
      - app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: epilanthanomai/lfweb:dev
    links:
      - app
    ports:
      - '80:80'
  app:
    image: epilanthanomai/polygraph:dev
    links:
      - db
    environment:
      POLYGRAPH_DB: postgresql://polygraph:polygraph@db/polygraph
    command: [bash, -c, "scripts/wait-for-port.sh db 5432 && npm run migrate && npm start"]
    ports:
      - '3000:3000'
  db:
    image: postgres
    environment:
      POSTGRES_USER: polygraph
      POSTGRES_PASSWORD: polygraph
